//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_DichVu
    {
        public int ma_HDDV { get; set; }
        public Nullable<int> ma_KH { get; set; }
        public Nullable<int> ma_NV { get; set; }
        public Nullable<bool> isDelete { get; set; }
    }
}
