//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ma_SP { get; set; }
        public Nullable<int> ma_DM { get; set; }
        public Nullable<int> ma_Loai { get; set; }
        public Nullable<int> ma_Hang { get; set; }
        public string mau_SP { get; set; }
        public Nullable<int> soluong_SP { get; set; }
    }
}
